### ISSUE TITLE
cann't add it

### ISSUE THREAD

**Issue by addtioe** [CraftTweaker/CraftTweaker#1111]
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: 無盡錠.zs}
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:3: Could not resolve <avaritia : resource : * 6>
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:4: Could not resolve <avaritia : resource : * 6>
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:7: Could not resolve <avaritia : resource : * 6>
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:8: Could not resolve <avaritia : resource : * 5>
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:9: Could not resolve <ores : ingotmithMinite : *>
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:9: Could not resolve <avaritia : resource : * 4>
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:9: Could not resolve <ores : ingotmithMinite : *>
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:10: Could not resolve <avaritia : resource : * 5>
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:4 > 2 methods available but none matches the parameters (any)
This is usually an error in your script, not in the mod
hide(ZenTypeNative: crafttweaker.item.IItemStack)
hide(ZenTypeNative: crafttweaker.liquid.ILiquidStack)
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:8 > cannot cast any[] to ZenTypeNative: crafttweaker.item.IIngredient
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:8 > cannot cast any[] to ZenTypeNative: crafttweaker.item.IIngredient
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:8 > cannot cast any[] to ZenTypeNative: crafttweaker.item.IIngredient
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:9 > cannot cast any[] to ZenTypeNative: crafttweaker.item.IIngredient
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:9 > cannot cast any[] to ZenTypeNative: crafttweaker.item.IIngredient
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:9 > cannot cast any[] to ZenTypeNative: crafttweaker.item.IIngredient
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:10 > cannot cast any[] to ZenTypeNative: crafttweaker.item.IIngredient
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:10 > cannot cast any[] to ZenTypeNative: crafttweaker.item.IIngredient
[INITIALIZATION][CLIENT][ERROR] 無盡錠.zs:10 > cannot cast any[] to ZenTypeNative: crafttweaker.item.IIngredient
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: 無盡錠.zs}: null
java.lang.NullPointerException
	at crafttweaker.mods.jei.JEI.removeAndHide(JEI.java:73)
	at 無盡錠.__script__(無盡錠.zs:3)
	at __ZenMain__.run(無盡錠)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:225)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_722_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by jaredlll08** [comment]
Follow the issue template.

**Comment by kindlich** [comment]
Use the issue template.
Also, you either use meta or wildcard meta, not both.
If you wanted to specify an amount that's after the Item Bracket handler
