### ISSUE TITLE
Mod doesn't load at all.

### ISSUE THREAD

**Issue by huhridge** [CraftTweaker/CraftTweaker#1329]
### Issue description

Using curseforge to load a modpack using this mod on the M1 MacBook Air, the mod refuses to load.
The java version is 1.8.0_74 and forge version is 34.1.42.
The error log is enclosed:
Mod File: CraftTweaker-1.16.3-7.0.0.48.jar
	Failure message: CraftTweaker (crafttweaker) has failed to load correctly
		java.lang.ArrayIndexOutOfBoundsException: -1
	Mod Version: 7.0.0.48
	Mod Issue URL: https://github.com/CraftTweaker/CraftTweaker/issues
	Exception message: java.lang.ArrayIndexOutOfBoundsException: -1
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2IntOpenCustomHashMap.rehash(Object2IntOpenCustomHashMap.java:1148) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenCustomHashMap.insert(Object2IntOpenCustomHashMap.java:305) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenCustomHashMap.put(Object2IntOpenCustomHashMap.java:313) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at net.minecraft.util.registry.SimpleRegistry.func_243537_a(SourceFile:81) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.SimpleRegistry.func_218382_a(SourceFile:72) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.SimpleRegistry.func_218381_a(SourceFile:103) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.item.crafting.IRecipeType.func_222147_a(SourceFile:20) ~[?:?] {re:classloading}
	at com.blamejared.crafttweaker.CraftTweaker.<init>(CraftTweaker.java:119) ~[?:7.0.0.48] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}

### Script used

n/a

### The crafttweaker.log file

doesn't exist/empty

### Minecraft version

1.16

### Forge version

34.1.42

### CraftTweaker version

7.0.0.48

### The latest.log file

https://gist.github.com/oharij/1eb95595ad4bc7f0a8f153504e424deb

**Comment by jaredlll08** [comment]
Do not upload your errors directly to github. It is nearly impossible to actual read them.


Update CraftTweaker, you're over 300 versions behind.
