### ISSUE TITLE
[1.12] Duplicate AT Causes Dev Env to be Unable to Run

### ISSUE THREAD

**Issue by ByThePowerOfScience** [CraftTweaker/CraftTweaker#1469]
### Issue description

https://github.com/CraftTweaker/CraftTweaker/issues/607
The above issue causes the error "java.util.zip.ZipException: duplicate entry: META-INF/crafttweaker_at.cfg" when attempting to load the 1.12 CraftTweaker jar from CurseMaven in dev.  Using the BlameJared Maven repository source or not wrapping the dependency in `fg.deobf` results in the AT not being loaded and the client halting due to an IllegalAccessError.

### Steps to reproduce

Use `fg.deobf("curse.maven:CraftTweaker-239197:3642364")` as any type of dependency.

### Buildscript used

https://paste.ofcode.org/gRn4ZJgcNkA3t4UkujkGeH

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

1.12.2-14.23.5.2860

### CraftTweaker version

CraftTweaker2-1.12-4.1.20.674.jar

### Other relevant information

Dep wrapped with `fg.deobf()`: https://pastebin.com/0VR9pNRc
Dep not wrapped with `fg.deobf()`: https://pastebin.com/9PRKjYQU

(Since Pastebin likes to spam-filter stacktraces:
Wrapped: (on Gradle sync)
`> Configure project :
[MixinGradle] Skipping eclipse integration, extension not found
Exception in thread "main" java.lang.RuntimeException: Unable to process entry 'META-INF/crafttweaker_at.cfg' due to an error when processing previous entry 'pack.mcmeta'
	at net.minecraftforge.installertools.SrgMcpRenamer.forEachZipEntry(SrgMcpRenamer.java:161)
	at net.minecraftforge.installertools.SrgMcpRenamer.process(SrgMcpRenamer.java:136)
	at net.minecraftforge.installertools.ConsoleTool.main(ConsoleTool.java:55)
Caused by: java.util.zip.ZipException: duplicate entry: META-INF/crafttweaker_at.cfg
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
	at net.minecraftforge.installertools.SrgMcpRenamer.lambda$process$6(SrgMcpRenamer.java:128)
	at net.minecraftforge.installertools.SrgMcpRenamer.lambda$process$8(SrgMcpRenamer.java:141)
	at net.minecraftforge.installertools.SrgMcpRenamer.forEachZipEntry(SrgMcpRenamer.java:159)
	... 2 more
Error getting artifact: curse.maven:CraftTweaker-239197:3642364_mapped_stable_39-1.12:null@jar from  DeobfuscatingRepo`

Not wrapped: (on client launch)
`Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.util.text.translation.LanguageMap.instance from class crafttweaker.mc1120.game.MCGame
	at crafttweaker.mc1120.game.MCGame.<clinit>(MCGame.java:34)
	at crafttweaker.mc1120.CraftTweaker.onConstruction(CraftTweaker.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)`

**Comment by jaredlll08** [comment]
Don't use curse maven as a maven.
https://maven.blamejared.com/

**Comment by ByThePowerOfScience** [comment]
Using the BlameJared Maven results in the AT not being loaded.

**Comment by jaredlll08** [comment]
Do you have dep ATs enabled?

https://github.com/jaredlll08/ModTweaker/blob/1.12/build.gradle#L41

**Comment by ByThePowerOfScience** [comment]
As far as I know?  Is there a special way you're supposed to do this?
I've looked everywhere and it seems like it's supposed to work out of the
box.

Edit: sorry, didn't see the file you linked! Thank you, I'll try that!

**Comment by ByThePowerOfScience** [comment]
That's not a thing in FG5, unfortunately.  I'll keep looking for a solution.

**Comment by jaredlll08** [comment]
As I said here https://github.com/CraftTweaker/CraftTweaker/issues/1459#issuecomment-1072114818

I know it works in the project I linked, I don't know if they found a solution though.
