### ISSUE TITLE
Warn Log: could not create Vfs.Dir from url

### ISSUE THREAD

**Issue by Laifsyn** [CraftTweaker/CraftTweaker#1472]
### Issue description

_**[15:19:29] [Render thread/WARN]: could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [magic-at:/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.**_
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:113) ~[org_reflections_reflections-0.10.2-7d96ec3b2ef8208a.jar:?]
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:95) ~[org_reflections_reflections-0.10.2-7d96ec3b2ef8208a.jar:?]
	at org.reflections.Reflections.lambda$scan$2(Reflections.java:176) ~[org_reflections_reflections-0.10.2-7d96ec3b2ef8208a.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[?:?]
	at org.reflections.Reflections.scan(Reflections.java:173) ~[org_reflections_reflections-0.10.2-7d96ec3b2ef8208a.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:126) ~[org_reflections_reflections-0.10.2-7d96ec3b2ef8208a.jar:?]
	at org.reflections.Reflections.<init>(Reflections.java:159) ~[org_reflections_reflections-0.10.2-7d96ec3b2ef8208a.jar:?]
	at com.blamejared.crafttweaker.platform.FabricPlatformHelper.lambda$static$4(FabricPlatformHelper.java:84) ~[CraftTweaker-fabric-1.18.2-9.1.98.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar:?]
	at com.blamejared.crafttweaker.platform.FabricPlatformHelper.findClassesWithAnnotation(FabricPlatformHelper.java:163) ~[CraftTweaker-fabric-1.18.2-9.1.98.jar:?]
	at com.blamejared.crafttweaker.platform.services.IPlatformHelper.findClassesWithAnnotation(IPlatformHelper.java:102) ~[CraftTweaker-fabric-1.18.2-9.1.98.jar:?]
	at com.blamejared.crafttweaker.impl.plugin.core.PluginManager.discoverPlugins(PluginManager.java:70) ~[CraftTweaker-fabric-1.18.2-9.1.98.jar:?]
	at com.blamejared.crafttweaker.impl.plugin.core.PluginManager.of(PluginManager.java:65) ~[CraftTweaker-fabric-1.18.2-9.1.98.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar:?]
	at com.blamejared.crafttweaker.CraftTweakerCommon.getPluginManager(CraftTweakerCommon.java:70) ~[CraftTweaker-fabric-1.18.2-9.1.98.jar:?]
	at com.blamejared.crafttweaker.CraftTweakerFabric.onInitialize(CraftTweakerFabric.java:19) ~[CraftTweaker-fabric-1.18.2-9.1.98.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) [fabric-loader-0.13.3.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:452) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]

### Script used

none

### The crafttweaker.log file

[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker/files/8498228/crafttweaker.log)

### Minecraft version

1.18

### Modloader

Fabric

### Modloader version

0.13.3

### CraftTweaker version

CraftTweaker-fabric-1.18.2-9.1.98

### The latest.log file

https://pastebin.com/sh3eCPZQ

**Comment by jaredlll08** [comment]
As suggested by @TheSilkMiner on discord, install ChocoASM and see if that works
