### ISSUE TITLE
[1.19.2] Ticking player crash when using craft tweaker to modify item attributes

### ISSUE THREAD

**Issue by Dyshonored** [CraftTweaker/CraftTweaker#1593]
### Issue description

The game crashes to desktop when I used a weapon with attributes modified by craft tweaker scripts
I used multiple scripts each doing specific things. But for bug report purposes I combined them into a single pastbin file (see script used section).
Below is the crash report.

Thank you for your time.

---- Minecraft Crash Report ----
// There are four lights!

Time: 2022-11-18 18:37:16
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at com.blamejared.crafttweaker.platform.services.IEventHelper.applyAttributeModifiers(IEventHelper.java:95) ~[CraftTweaker-forge-1.19.2-10.0.16.jar%23150!/:10.0.16] {re:classloading}
	at com.blamejared.crafttweaker.impl.event.CTCommonEventHandler.attribute(CTCommonEventHandler.java:64) ~[CraftTweaker-forge-1.19.2-10.0.16.jar%23150!/:10.0.16] {re:classloading}
	at com.blamejared.crafttweaker.impl.event.__CTCommonEventHandler_attribute_ItemAttributeModifierEvent.invoke(.dynamic) ~[CraftTweaker-forge-1.19.2-10.0.16.jar%23150!/:10.0.16] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.common.ForgeHooks.getAttributeModifiers(ForgeHooks.java:1087) ~[forge-1.19.2-43.1.30-universal.jar%23170!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41638_(ItemStack.java:909) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.mlib.json:MixinItemStack,pl:mixin:A}
	at com.magistuarmory.item.MedievalWeaponItem.m_6883_(MedievalWeaponItem.java:174) ~[%5B1.19.x%5D-Epic-Knights-Armor-and-Weapons-6.7v.jar%23145!/:1.0] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:508) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.mlib.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:228) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:499) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:PlayerEntityMixin,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityMixin,pl:mixin:APP:nochatreports.mixins.json:server.MixinPlayer,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayer,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,re:classloading,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityInject,pl:mixin:APP:mixins.mlib.json:MixinLivingEntity,pl:mixin:APP:responsiveshields.mixin.json:MixinTicksConst,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:PlayerEntityMixin,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityMixin,pl:mixin:APP:nochatreports.mixins.json:server.MixinPlayer,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayer,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at com.blamejared.crafttweaker.platform.services.IEventHelper.applyAttributeModifiers(IEventHelper.java:95) ~[CraftTweaker-forge-1.19.2-10.0.16.jar%23150!/:10.0.16] {re:classloading}
	at com.blamejared.crafttweaker.impl.event.CTCommonEventHandler.attribute(CTCommonEventHandler.java:64) ~[CraftTweaker-forge-1.19.2-10.0.16.jar%23150!/:10.0.16] {re:classloading}
	at com.blamejared.crafttweaker.impl.event.__CTCommonEventHandler_attribute_ItemAttributeModifierEvent.invoke(.dynamic) ~[CraftTweaker-forge-1.19.2-10.0.16.jar%23150!/:10.0.16] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.common.ForgeHooks.getAttributeModifiers(ForgeHooks.java:1087) ~[forge-1.19.2-43.1.30-universal.jar%23170!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41638_(ItemStack.java:909) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.mlib.json:MixinItemStack,pl:mixin:A}
	at com.magistuarmory.item.MedievalWeaponItem.m_6883_(MedievalWeaponItem.java:174) ~[%5B1.19.x%5D-Epic-Knights-Armor-and-Weapons-6.7v.jar%23145!/:1.0] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:508) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.mlib.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:228) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:499) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:PlayerEntityMixin,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityMixin,pl:mixin:APP:nochatreports.mixins.json:server.MixinPlayer,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayer,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,re:classloading,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityInject,pl:mixin:APP:mixins.mlib.json:MixinLivingEntity,pl:mixin:APP:responsiveshields.mixin.json:MixinTicksConst,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:PlayerEntityMixin,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityMixin,pl:mixin:APP:nochatreports.mixins.json:server.MixinPlayer,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayer,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 119
	Entity Name: Dyshonoured
	Entity's Exact location: -48.93, 70.00, 0.65
	Entity's Block location: World: (-49,70,0), Section: (at 15,6,0 in -4,4,0; chunk contains blocks -64,-64,0 to -49,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23165!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 875327464 bytes (834 MiB) / 2348810240 bytes (2240 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=31.0.12029.4013
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23990.34
	Virtual memory used (MB): 14905.45
	Swap memory total (MB): 7680.00
	Swap memory used (MB): 24.39
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Dyshonoured'/119, l='ServerLevel[New World]', x=-48.93, y=70.00, z=0.65]]
	Data Packs: vanilla, mod:diamondingots, mod:magistuarmory, mod:dusk (incompatible), mod:nochatreports (incompatible), mod:shouldersurfing (incompatible), mod:playeranimator (incompatible), mod:majruszlib, mod:jei (incompatible), mod:diamondshards, mod:majruszsdifficulty, mod:jeresources (incompatible), mod:incontrol (incompatible), mod:crafttweaker (incompatible), mod:cloth_config (incompatible), mod:bettercombat (incompatible), mod:combatroll, mod:forge, mod:openloader (incompatible), mod:shutupexperimentalsettings (incompatible), mod:controlling (incompatible), mod:responsiveshields (incompatible), data/engarde datapack.zip (incompatible)
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.19.2-forge-43.1.30
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.1.30.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.30.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.1.30.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.1.30.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.30.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		diamondingots-1.4-forge.58+1.19.2.jar             |Diamond Ingots                |diamondingots                 |1.4-forge.58+1.19.2 |DONE      |Manifest: NOSIGNATURE
		[1.19.x]-Epic-Knights-Armor-and-Weapons-6.7v.jar  |Epic Knights: Armor and Weapon|magistuarmory                 |1.0                 |DONE      |Manifest: NOSIGNATURE
		dusk-1.19.2-2.4.jar                               |Dusk Mod                      |dusk                          |1.19.2-2.4          |DONE      |Manifest: NOSIGNATURE
		NoChatReports-FORGE-1.19.2-v1.5.1.jar             |No Chat Reports               |nochatreports                 |1.19.2-v1.5.1       |DONE      |Manifest: NOSIGNATURE
		ShoulderSurfing-Forge-1.19.2-2.2.16.jar           |Shoulder Surfing              |shouldersurfing               |1.19.2-2.2.16       |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.0-test4.jar        |Player Animator               |playeranimator                |0.4.0-test4         |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.19.2-2.17.0.jar                 |Majrusz Library               |majruszlib                    |2.17.0              |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.4.0.286.jar                   |Just Enough Items             |jei                           |11.4.0.286          |DONE      |Manifest: NOSIGNATURE
		diamondshards-forge-1.19.2-v1.0.4.jar             |Diamond Shards                |diamondshards                 |1.0.4               |DONE      |Manifest: NOSIGNATURE
		majruszs-difficulty-1.19.2-1.5.11.jar             |Majrusz's Progressive Difficul|majruszsdifficulty            |1.5.11              |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.19.2-1.1.0.179.jar          |Just Enough Resources         |jeresources                   |1.1.0.179           |DONE      |Manifest: NOSIGNATURE
		incontrol-1.19-7.0.15.jar                         |InControl                     |incontrol                     |1.19-7.0.15         |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.19.2-10.0.16.jar             |CraftTweaker                  |crafttweaker                  |10.0.16             |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.4.5+1.19.jar                 |Better Combat                 |bettercombat                  |1.4.5+1.19          |DONE      |Manifest: NOSIGNATURE
		combatroll-forge-1.0.8+1.19.jar                   |Combat Roll                   |combatroll                    |1.0.8+1.19          |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.1.30-universal.jar                |Forge                         |forge                         |43.1.30             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		OpenLoader-Forge-1.19.2-15.0.1.jar                |OpenLoader                    |openloader                    |15.0.1              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		shutupexperimentalsettings-1.0.5.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.5               |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.19.2-10.0+7.jar               |Controlling                   |controlling                   |10.0+7              |DONE      |Manifest: NOSIGNATURE
		responsiveshields-2.1-mc1.17-18-19.x.jar          |Responsive Shields            |responsiveshields             |2.1                 |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2f7c7b11-7404-4b66-a109-7abeeeef0b80
	FML: 43.1
	Forge: net.minecraftforge:43.1.30

### Steps to reproduce

Write a CT script modifying item attributes (following craft tweaker documentations)
Wield the item that has been modified in-game
Crash to desktop

### Script used

https://pastebin.com/WQMrKVAh

### The crafttweaker.log file

https://pastebin.com/iST22Af9

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.1.30

### CraftTweaker version

10.0.16

### The latest.log file

https://pastebin.com/J0MQn41E

**Comment by Dyshonored** [comment]
I updated forge to the latest version and got the same result

**Comment by Dyshonored** [comment]
Sometimes the crash does not happen immediately after equipping a modified weapon
But it generally happens within 5 minutes or so. This results in the same crash report

**Comment by Noobulus** [comment]
Seems like this crash also happens on Quilt 0.17.8 with CT-modified armor.
[Prism Log (latest.log + crash report)](https://mclo.gs/72ThNVP)
[Script Used](https://hastebin.com/uguwejinut.js)
