### ISSUE TITLE
crash on launch in dev environment

### ISSUE THREAD

**Issue by st0x0ef** [CraftTweaker/CraftTweaker#1617]
### Issue description

the game crash when I tried to launch the game with runclient in my dev environment

crashlog : 

at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
	at com.blamejared.crafttweaker.impl.plugin.crafttweaker.BracketParserRegistrationManager.addRegistrationCandidate(BracketParserRegistrationManager.java:100) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.impl.plugin.crafttweaker.BuiltinCraftTweakerPlugin.lambda$registerBracketParsers$1(BuiltinCraftTweakerPlugin.java:105) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at com.blamejared.crafttweaker.impl.plugin.crafttweaker.ZenClassGatherer.onCandidates(ZenClassGatherer.java:39) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.impl.plugin.crafttweaker.BuiltinCraftTweakerPlugin.registerBracketParsers(BuiltinCraftTweakerPlugin.java:104) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.impl.plugin.core.DecoratedCraftTweakerPlugin.registerBracketParsers(DecoratedCraftTweakerPlugin.java:47) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.impl.plugin.core.PluginManager.lambda$onEach$31(PluginManager.java:329) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at com.blamejared.crafttweaker.impl.plugin.core.PluginManager.lambda$onEach$32(PluginManager.java:327) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.impl.plugin.core.BracketParserRegistrationHandler.of(BracketParserRegistrationHandler.java:33) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.impl.plugin.core.PluginManager.lambda$handleZenDataRegistration$8(PluginManager.java:188) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.impl.plugin.core.PluginManager.verifying(PluginManager.java:319) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.impl.plugin.core.PluginManager.handleZenDataRegistration(PluginManager.java:186) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.impl.plugin.core.PluginManager.loadPlugins(PluginManager.java:122) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at com.blamejared.crafttweaker.CraftTweakerForge.<init>(CraftTweakerForge.java:16) ~[CraftTweaker-forge-1.19.2-10.1.33_mapped_official_1.19.2.jar%23191!/:10.1.33] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.1.jar%23181!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.1.jar%23184!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

### Steps to reproduce

1. integrate this mod to another mod in 1.19.2
2. click on runclient to start the game

### Script used

https://github.com/gabrielgaudreault/Beyond-Earth

### The crafttweaker.log file

the game does not launch so no log file

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

43.2.1

### CraftTweaker version

10.1.33

### Other relevant information

I've tried with the version 10.1.31 and 10.1.32 too

### The latest.log file

the game does not launch so no log file

**Comment by jaredlll08** [comment]
I need the full log, as a paste, not pasted into github, and your build.gradle with the changes you made to add CraftTweaker.

Also there should be a latest.log file regardless of if it crashed.

**Comment by jaredlll08** [comment]
The issue is you are using an older version of mekanism that was built against an older CraftTweaker version, you need to update mekanism to `10.3.8.477`
