### ISSUE TITLE
ct dump recipes NullPointerException 

### ISSUE THREAD

**Issue by schindlershadow** [CraftTweaker/CraftTweaker#1761]
### Issue description

running /ct dump recipes gives an error `[CHAT] An unexpected error occurred trying to execute that command` and only part of the recipes are dumped to the ct logs
MC version 1.21.1

Error in logs
```
[30Aug2024 18:47:03.820] [Server thread/ERROR] [net.minecraft.commands.Commands/]: Command exception: /ct recipes
java.lang.NullPointerException: Cannot invoke "com.blamejared.crafttweaker.api.data.IData.asString()" because "value" is null
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.api.data.visitor.DataToStringVisitor.visitMap(DataToStringVisitor.java:171) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.api.data.visitor.DataToStringVisitor.visitMap(DataToStringVisitor.java:26) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.api.data.MapData.accept(MapData.java:221) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.api.data.IData.getAsString(IData.java:547) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.api.data.MapData.toString(MapData.java:268) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at java.base/java.lang.String.valueOf(Unknown Source) ~[?:?]
	at java.base/java.lang.StringBuilder.append(Unknown Source) ~[?:?]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.api.util.ItemStackUtil.lambda$getCommandString$0(ItemStackUtil.java:37) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.api.util.ItemStackUtil.getCommandString(ItemStackUtil.java:33) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.api.util.ItemStackUtil.getCommandString(ItemStackUtil.java:24) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.impl.recipe.handler.type.vanilla.ShapedRecipeHandler.dumpToCommandString(ShapedRecipeHandler.java:39) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.impl.command.type.RecipeCommands.dump(RecipeCommands.java:183) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.impl.command.type.RecipeCommands.lambda$dumpRecipe$18(RecipeCommands.java:165) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source) ~[?:?]
	at java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.impl.command.type.RecipeCommands.dumpRecipe(RecipeCommands.java:166) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.impl.command.type.RecipeCommands.lambda$dumpRecipes$17(RecipeCommands.java:151) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.impl.command.type.RecipeCommands.dumpRecipes(RecipeCommands.java:151) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.impl.command.type.RecipeCommands.dumpRecipes(RecipeCommands.java:94) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at TRANSFORMER/crafttweaker@21.0.2/com.blamejared.crafttweaker.impl.command.type.RecipeCommands.lambda$registerCommands$0(RecipeCommands.java:45) ~[CraftTweaker-neoforge-1.21.1-21.0.2.jar%23392!/:21.0.2]
	at MC-BOOTSTRAP/brigadier@1.3.10/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar%23139!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:29) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:8) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:107) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.Commands.executeCommandInContext(Commands.java:363) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.Commands.performCommand(Commands.java:284) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:1281) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$7(ServerGamePacketListenerImpl.java:1268) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:821) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:826) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23356!/:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

### Steps to reproduce

run /ct dump recipes

### Script used

NA

### The crafttweaker.log file

https://pastebin.com/raw/gMjHdJub

### Minecraft version

Other

### Modloader

NeoForge

### Modloader version

21.1.26

### CraftTweaker version

CraftTweaker-neoforge-1.21.1-21.0.2

### The latest.log file

https://pastebin.com/raw/K97hbV6L

**Comment by schindlershadow** [comment]
After a lot of testing I found that this was caused by GregTech and Iron's Spells 'n Spellbooks

**Comment by jaredlll08** [comment]
You mention gregtech, however I don't see gregtech in your latest.log file.

I can not reproduce this issue with just Iron's Spells 'n Spellbooks.

**Comment by jaredlll08** [comment]
I'm going to close this due to no reply.
