### ISSUE TITLE
Error when using "/ct biomes" command

### ISSUE THREAD

**Issue by Bulldog83** [CraftTweaker/CraftTweaker#526]
- Minecraft: 1.12.2
- Forge: 14.23.3.2673
- Crafttweaker: 1.12-4.1.8

Mods with biomes are uses:
BiomesOPlenty-1.12.2-7.0.1.2383
defiledlands-1.12.2-1.3.0
NetherEx-1.12-2.1.14.15
AbyssalCraft-1.12.2-1.9.4.8
appliedenergistics2-rv5-stable-11 (storage cell)

Error log:
```
[13:56:06] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[13:56:06] [Server thread/WARN]: Couldn't process command: ct biomes
java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at crafttweaker.mc1120.world.MCBiome.getName(MCBiome.java:20) ~[MCBiome.class:?]
	at crafttweaker.mc1120.commands.Commands$18.executeCommand(Commands.java:553) ~[Commands$18.class:?]
	at crafttweaker.mc1120.commands.CTChatCommand.func_184881_a(CTChatCommand.java:85) ~[CTChatCommand.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

**Comment by kindlich** [comment]
You are on a server, correct?
Try if it works in single player.

**Comment by Bulldog83** [comment]
Yes, it's a dedicated server.
In single player command works fine.
