### ISSUE TITLE
[question] Why I have NPE in this script?

### ISSUE THREAD

**Issue by Bulldog83** [CraftTweaker/CraftTweaker#578]
I have NPE in [this](https://gist.github.com/Bulldog83/89ebac8f5570dc1628b76e6196d147cb) script, but I can't undestand why.

```
[INITIALIZATION][SERVER][INFO] [crafttweaker | SIDE_SERVER]: Loading Script: {[0:crafttweaker]: ArtisanWorktables\BiblioCraft.zs}
[INITIALIZATION][SERVER][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: ArtisanWorktables\BiblioCraft.zs}: null
java.lang.NullPointerException
	at stanhebben.zenscript.type.natives.JavaMethod.rematch(JavaMethod.java:134)
	at stanhebben.zenscript.expression.ExpressionCallVirtual.<init>(ExpressionCallVirtual.java:24)
	at stanhebben.zenscript.type.natives.ZenNativeMember$InstanceGetValue.eval(ZenNativeMember.java:80)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:27)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:19)
	at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:149)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:164)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:68)
	at crafttweaker.runtime.CrTTweaker.load(CrTTweaker.java:62)
	at crafttweaker.CrafttweakerImplementationAPI.load(CrafttweakerImplementationAPI.java:115)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_951_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
```
For example, [this](https://gist.github.com/Bulldog83/c880641b19e8120c88c0edde4c33b555) script works fine.

**Comment by jaredlll08** [comment]
You know we have an issue template right?

Use it.

**Comment by Bulldog83** [comment]
And here the bureaucracy ... : (

**Comment by jaredlll08** [comment]
Okay, what version are you using? Is this on a server? What Mc version? What Forge version?

If you want to make my life easier and want help then the least you could do is use the template I gave you when you created the issue.

If you want to be uncooperative then just tell me and I'll lock this issue now :)

**Comment by Bulldog83** [comment]
Ok, I'm sorry. I'm just try somthing else, and, if problem still occurs, I'll post new issue in accordance with puttern.
