### ISSUE TITLE
No such member: mekanism in MC 1.12.2

### ISSUE THREAD

**Issue by enricotagliavini** [CraftTweaker/CraftTweaker#661]
#### Issue Description:
When trying to add recipes to mekanism's crusher the script loading fails with "No such member: mekanism", although the mod seems to be correctly detected by looking at the output of /ct mods

#### What happens:
Trying to use https://minecraft.curseforge.com/projects/mekanism-pams-harvestcraft-compatibility with CraftTweaker 4.1.11. For each line in the file .zs file starting with mods.mekanism I get an error

```
[INITIALIZATION][CLIENT][ERROR] 03_pams_harvestcraft_mekanism_crusher.zs:6 > No such member: mekanism
```

And, at the very end of the log file
```
[INITIALIZATION][CLIENT][ERROR] 03_pams_harvestcraft_mekanism_crusher.zs:224 > No such member: mekanism
[INITIALIZATION][CLIENT][INFO] Initializing '03_pams_harvestcraft_mekanism_crusher.zs...
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: 03_pams_harvestcraft_mekanism_crusher.zs}: Truncated class file
java.lang.ClassFormatError: Truncated class file
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at stanhebben.zenscript.ZenModule$MyClassLoader.loadClass(ZenModule.java:417)
        at 03_pams_harvestcraft_mekanism_crusher.__script__(03_pams_harvestcraft_mekanism_crusher.zs:6)
        at __ZenMain__.run(03_pams_harvestcraft_mekanism_crusher)
        at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:218)
        at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:101)
        at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:68)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_671_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
        at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3929)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

#### What you expected to happen:
Script should load with no errors

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Original script can be downloaded from https://minecraft.curseforge.com/projects/mekanism-pams-harvestcraft-compatibility , but I'll paste a shorter version here with only three lines for quick reference

```
#Pam's HarvestCraft & Mekanism: Pam's HarvestCraft Plants, Seeds, and Saplings now create biofuel:
#author: DarethMC
print("Initializing '03_pams_harvestcraft_mekanism_crusher.zs...");

val biofuel = <mekanism:biofuel>;
mods.mekanism.crusher.addRecipe(<harvestcraft:blackberryitem>, biofuel *3);
mods.mekanism.crusher.addRecipe(<harvestcraft:blackberryseeditem>, biofuel *2);
mods.mekanism.crusher.addRecipe(<harvestcraft:blueberryitem>, biofuel *3);
```

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://paste.fedoraproject.org/paste/kJQNV1dq2Y~9lwArn-PBPg

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768
- Crafttweaker: 4.1.11
- Using a server: happens both in SP and when using a server
- If yes, does the client have the exact same scripts? Yes

#### Your most recent log file where the issue was present: 

Started the game, logged in, saw the error, logged out.
https://paste.fedoraproject.org/paste/oX1R7cg5VvDD0XsDY8Thew

**Comment by jaredlll08** [comment]
We don't add mekanism support.

**Comment by enricotagliavini** [comment]
Oh sorry, didn't meant to bother. Should I report this to Mekanism mod instead?

**Comment by jaredlll08** [comment]
yea
