### ISSUE TITLE
NullPointerException on player.teleport call

### ISSUE THREAD

**Issue by Jummit** [CraftTweaker/CraftTweaker#924]
#### Issue Description:
There is a NullPointerException when calling player.teleport.
Stack trace:
```
java.lang.NullPointerException: null
at net.minecraft.command.EntitySelector.func_179654_a(EntitySelector.java:219) ~[bq.class:?]
at net.minecraft.command.EntitySelector.matchEntitiesDefault(EntitySelector.java:144) ~[bq.class:?]
net.minecraftforge.common.command.SelectorHandlerManager$1.matchEntities(SelectorHandlerManager.java:62) ~[SelectorHandlerManager$1.class:?]
net.minecraftforge.common.command.SelectorHandlerManager.matchEntities(SelectorHandlerManager.java:129) ~[SelectorHandlerManager.class:?]
at net.minecraft.command.EntitySelector.func_179656_b(EntitySelector.java:124) ~[bq.class:?]
at net.minecraft.command.EntitySelector.func_179652_a(EntitySelector.java:96) ~[bq.class:?]
at net.minecraft.command.CommandBase.func_184884_a(CommandBase.java:292) ~[bi.class:?]
at net.minecraft.command.CommandBase.func_184885_b(CommandBase.java:287) ~[bi.class:?]
at net.minecraft.command.CommandTP.func_184881_a(SourceFile:48) ~[ec.class:?]
at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
at crafttweaker.mc1120.command.MCCommandManager.executeCommand(MCCommandManager.java:22) [MCCommandManager.class:?]
```
#### Script used
`player.teleport(crafttweaker.util.Position3f.create(7.0f, 66.0f, 134.0f))`
https://pastebin.com/icwY6Mtn

#### crafttweaker.log file
https://pastebin.com/icwY6Mtn

____
#### Affected Versions
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 2-1.12-4.1.20
- Using a server: no

#### Most recent log file where the issue was present
https://pastebin.com/ZuBfqMaV

**Comment by jaredlll08** [comment]
well considering `player.teleport()` doesn't use commands, I fail to see how the code you provided could cause that issue.
